steps:
- id: download-dataset
  uses: docker://horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu
  args: ["python", "./workflows/mnist/scripts/download_dataset.py"]

- id: verify-dataset
  uses: docker://alpine:3.9.5
  args: ["./workflows/mnist/scripts/verify_dataset.sh"]

- id: run-training
  uses: docker://horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu
  args: ["python", "./workflows/mnist/scripts/run_training.sh"]
  env:
    NUM_EPOCHS: '1'
    BATCH_SIZE: '128'
    DATASET_REDUCTION: '0.1'
