steps:
- id: download-dataset
  uses: docker://gw000/keras
  args: ["python", "./workflows/local/scripts/download_dataset.py"]

- id: verify-dataset
  uses: docker://alpine:3.9.5
  args: ["./workflows/local/scripts/verify_dataset.sh"]

- id: run-training
  uses: docker://gw000/keras
  args: ["./workflows/local/scripts/run_training.sh"]
  env:
    NUM_EPOCHS: '1'
    BATCH_SIZE: '128'
    DATASET_REDUCTION: '0.1'
