steps:
- id: plot
  uses: docker://jupyter/datascience-notebook:python-3.8.5
  runs: [jupyter]
  args: ["nbconvert", "--execute", "--to=notebook", "./results/plot.ipynb"]
  options:
    ports:
      8888/tcp: 8888

- id: build
  uses: docker://ivotron/pandoc:2.3.1
  dir: /workspace/paper
  runs: [
    "pandoc/entrypoint.sh",
    "--standalone",
    "--variable=urlcolor:cyan",
    "--metadata=monofont-size:scriptsize",
    "--from=markdown+smart",
    "--template=pandoc/template.latex",
    "--csl=pandoc/IEEE.csl",
    "--output=paper.pdf",
    "--highlight-style=tango",
    "--bibliography=refs.bib",
    "--metadata=IEEETran:true",
    "--metadata=documentclass:IEEETran",
    "--metadata=classoption:conference",
    "--metadata=natbib:false",
    "--metadata=urlcolor:black",
    "--metadata=usedefaultspacing:false",
    "--metadata=numbersections:true",
    "--metadata=secPrefix:section",
    "--filter=pandoc/pandoc-tabularize.py",
    "--filter=pandoc-crossref",
    "--filter=pandoc-citeproc",
    "paper.md"
  ]
